### ISSUE TITLE
when typing, everything appears 6 characters to the left of the cursor

### ISSUE THREAD

**Issue by sabernar** [faceleg/ACEView#20]
When you place the cursor to type, and then start typing, the letters appear 6 characters to the left of the cursor. In the attached screenshot, you can see the cursor and you can see the 'xxx' that was typed and where it was inserted.

![screen shot 2013-11-19 at 9 16 12 pm](https://f.cloud.github.com/assets/97241/1579664/f30d8528-51a2-11e3-9efc-3c23af1f70dd.png)

**Comment by planerde** [comment]
I just had the exact same issue.
kikko088's fix worked for me too, but I think this issue should be addressed!?

**Comment by faceleg** [comment]
Agree this should be done. I'm short of time at the moment.

The ACE editor is a submodule, located: https://github.com/faceleg/ACEView/tree/master/ACEView/Dependencies

If someone bumps that and submits a PR I'll gladly accept!

**Comment by faceleg** [comment]
@planerde's PR #33 should have fixed this!
