### ISSUE TITLE
Create next tag/podspec?

### ISSUE THREAD

**Issue by mmattozzi** [faceleg/ACEView#31]
Hi... great library, easy to use and fast... thanks! 

It seems like there have been a pretty decent amount of updates since the 0.0.4 release. Do you think you're ready to create a 0.0.5 release and push it to cocoapods? In particular, I'd like to use the setReadOnly method, but I'm sure there's some other good stuff in there since the last reason too. 

Keep up the good work!

**Comment by faceleg** [comment]
Definitely keen on this! Also be great to make sure search/replace works properly. I won't have time to do this right now - but if you (or someone else) did then I wouold be happy to push to cocoapods

**Comment by faceleg** [comment]
This should be done - could you verify?

**Comment by mmattozzi** [comment]
Did you push to the pod specs repo? When I bumped the version number I got the message
```
- `ACEView (~> 0.0.5)` required by `Podfile`
```

I still only see version 0.0.4 on the cocoapods site: http://cocoapods.org/?q=on%3Aosx%20aceview

**Comment by faceleg** [comment]
No I had to reapply for ownership  :(

**Comment by mmattozzi** [comment]
No problem, thanks... for anybody else looking to pull in the latest and greatest in the meantime, it's easy to do with the following line in your Podfile:
```
pod 'ACEView', :git => 'git@github.com:faceleg/ACEView.git', :commit => '1a6fac895d2fde98da95dacb618403939bb2dce3', :submodules => true
```

**Comment by faceleg** [comment]
Can you not specify master?

**Comment by mmattozzi** [comment]
Yeah, omitting the :commit parameter will always give you master. It makes more sense to me to lock in to a specific commit similar to how one might lock into a specific version, so you at least know what you're building against. Personal preference, I suppose.

**Comment by faceleg** [comment]
But but I thought you trusted me

**Comment by markeissler** [comment]
Perhaps a better way would be to use:

```
pod "ACEView", :git => "https://github.com/faceleg/ACEView.git",
  :tag => "0.0.5",
  :submodules => true
```

**Comment by faceleg** [comment]
Podspec should be updated

**Comment by mmattozzi** [comment]
Awesome, thanks!
