### ISSUE TITLE
Printing does not work

### ISSUE THREAD

**Issue by microtherion** [faceleg/ACEView#36]
I would like to implement printing in my ACEView using app, but for some reason, only a frame gets printed (this behavior is exhibited by the example app as well). 

I'm somewhat puzzled by this, as WebViews as such certainly should be printable, and if I load e.g. the ace kitchen sink demo http://ace.c9.io/build/kitchen-sink.html into a WebView, it prints just fine.

**Comment by faceleg** [comment]
Sorry for the delay in responding.

How are you printing this (example Objc code)?

**Comment by microtherion** [comment]
I tried a number of approaches, but the easiest way to demonstrate the problem is simply to build ACEViewExample and hit "Print".

**Comment by faceleg** [comment]
There is this thread here, looks like other people have had a similar problem: https://groups.google.com/forum/#!topic/ace-discuss/Ojm6AdVm9w8

**Comment by microtherion** [comment]
Thanks for the pointer, I'll try something along those lines.

It is absolutely possible to override the default print workflow, and in fact for high quality printing (headers/footers, default pagination), that is probably going to be necessary anyway, but first the basic functionality has to work. I'll look into it.

**Comment by faceleg** [comment]
That's great - if at all possible do you think you would be able to add your code as a "print" method in ACEVIew? That way you solve the problem once for everybody ;)

**Comment by microtherion** [comment]
Yes, my plan is definitely to contribute upstream if I come up with a workable solution.

**Comment by faceleg** [comment]
:dancer:

**Comment by microtherion** [comment]
See #39. I intend to add some fancier formatting, but here's the basic functionality so we get an idea whether we're on the same page (sic!) with this.

**Comment by faceleg** [comment]
We're on the same page :page_facing_up:

**Comment by faceleg** [comment]
Thanks for teaching me about `@optional`!

**Comment by microtherion** [comment]
Added a second (and hopefully final, as far as my needs are concerned) set of printing changes in #42. This allows fairly sophisticated headers & footers, although `ACEView` adds just the mechanism, leaving the actual formatting to clients (example formatting added to `ACE View Example`).

**Comment by faceleg** [comment]
Thanks! You rock!
