### ISSUE TITLE
Example app building

### ISSUE THREAD

**Issue by genericptr** [faceleg/ACEView#41]
I wasn't able to build the example app without first having to find an "emmit" and "ace" project. I couldn't find those but I did find the compiled app in the package, however I had to add the framework manually into the bundle.

That would be nicer if it built out of the box for easy testing because on a lazier day I may have skipped this really cool project. Thanks man!

**Comment by faceleg** [comment]
Did you install the git submodules?

**Comment by faceleg** [comment]
I'm going to assume you got this sorted.
