### ISSUE TITLE
Find and click location issue

### ISSUE THREAD

**Issue by vladubogdan** [faceleg/ACEView#6]
When find bar is visible (that is when you press Command-F) clicking location is wrong. You can test this very simple by making the find bar visible and then trying to select a word by double clicking.

**Comment by jmartyniak** [comment]
@faceleg & @vladubogdan  It looks like some of the changes that have been suggested here have been made to AceView, however they don't work.  Or at least the find bar doesn't come up in the AceView, either in my custom code or in the sample application.

Any ideas?
